@php
    use App\Enums\ImageVariant;
    use App\Filament\Support\ArticleRichContent;
    use Illuminate\Support\Facades\Storage;
    use Illuminate\Support\Str;

    $blocks = is_array($getState()) ? $getState() : [];

    // The stored path is the Original (suffix-less) variant; derive the smaller
    // -mobile.webp sibling generated by the image pipeline.
    $mobileVariant = fn (string $path): string => str_ends_with($path, '.webp')
        ? Str::replaceLast('.webp', ImageVariant::Mobile->fileSuffix() . '.webp', $path)
        : $path;
@endphp

<x-dynamic-component :component="$getEntryWrapperView()" :entry="$entry">
    <div class="article-content-preview">
        @forelse ($blocks as $block)
            @php
                $type = $block['type'] ?? null;
                $data = $block['data'] ?? [];
            @endphp

            @switch($type)
                @case('richText')
                    <div class="acp-block acp-richtext">
                        {{ ArticleRichContent::renderer($data['content'] ?? '') }}
                    </div>
                    @break

                @case('image')
                    @php
                        $path = $data['image'] ?? null;
                        $caption = $data['caption'] ?? null;
                    @endphp
                    @if (filled($path))
                        <figure class="acp-block acp-figure">
                            <img
                                src="{{ Storage::disk('public')->url($mobileVariant($path)) }}"
                                alt="{{ $data['alt'] ?? '' }}"
                                loading="lazy"
                            >
                            @if (filled($caption))
                                <figcaption>{{ $caption }}</figcaption>
                            @endif
                        </figure>
                    @endif
                    @break

                @case('faq')
                    <div class="acp-block acp-faq">
                        @if (filled($data['heading'] ?? null))
                            <h3 class="acp-faq-heading">{{ $data['heading'] }}</h3>
                        @endif

                        @foreach (($data['items'] ?? []) as $item)
                            <details class="acp-faq-item">
                                <summary>{{ $item['question'] ?? '' }}</summary>
                                <div class="acp-faq-answer">
                                    {{ ArticleRichContent::renderer($item['answer'] ?? '') }}
                                </div>
                            </details>
                        @endforeach
                    </div>
                    @break
            @endswitch
        @empty
            <p class="acp-empty">This article has no content yet.</p>
        @endforelse
    </div>
</x-dynamic-component>

@once
    <style>
        /* Self-contained styling for the article content preview. The admin panel does
           not ship the Tailwind Typography plugin, so rich-text HTML is styled here
           directly rather than relying on `prose`. */
        .article-content-preview {
            --acp-border: rgb(228 228 231);          /* zinc-200 */
            --acp-muted: rgb(113 113 122);           /* zinc-500 */
            --acp-accent: rgb(217 119 6);            /* amber-600 (panel primary) */
            font-size: 0.95rem;
            line-height: 1.7;
        }
        .dark .article-content-preview {
            --acp-border: rgb(255 255 255 / 0.1);
            --acp-muted: rgb(161 161 170);           /* zinc-400 */
            --acp-accent: rgb(251 191 36);           /* amber-400 */
        }

        /* Padding between blocks + a slight separator between them. */
        .article-content-preview .acp-block {
            padding: 1.5rem 0;
        }
        .article-content-preview .acp-block + .acp-block {
            border-top: 1px solid var(--acp-border);
        }
        .article-content-preview .acp-block:first-child {
            padding-top: 0;
        }

        /* Rich text typography (restores element styling stripped by Preflight). */
        .acp-richtext :is(h1, h2, h3, h4) {
            font-weight: 600;
            line-height: 1.3;
            margin: 1.25rem 0 0.5rem;
        }
        .acp-richtext h1 { font-size: 1.6rem; }
        .acp-richtext h2 { font-size: 1.35rem; }
        .acp-richtext h3 { font-size: 1.15rem; }
        .acp-richtext :first-child { margin-top: 0; }
        .acp-richtext p { margin: 0.75rem 0; }
        .acp-richtext :is(ul, ol) { margin: 0.75rem 0; padding-left: 1.5rem; }
        .acp-richtext ul { list-style: disc; }
        .acp-richtext ol { list-style: decimal; }
        .acp-richtext li { margin: 0.25rem 0; }
        .acp-richtext a { color: var(--acp-accent); text-decoration: underline; }
        .acp-richtext blockquote {
            margin: 1rem 0;
            padding-left: 1rem;
            border-left: 3px solid var(--acp-border);
            color: var(--acp-muted);
        }
        .acp-richtext :is(strong, b) { font-weight: 600; }

        /* Images: -mobile variant, centered, capped, with a muted caption. */
        .acp-figure { text-align: center; }
        .acp-figure img {
            max-width: 100%;
            height: auto;
            border-radius: 0.5rem;
            display: inline-block;
        }
        .acp-figure figcaption {
            margin-top: 0.5rem;
            font-size: 0.85rem;
            font-style: italic;
            color: var(--acp-muted);
        }

        /* FAQ: standout heading + accordion cards. */
        .acp-faq-heading {
            font-size: 1.3rem;
            font-weight: 700;
            padding-bottom: 0.5rem;
            margin-bottom: 1rem;
            border-bottom: 2px solid var(--acp-accent);
        }
        .acp-faq-item {
            border: 1px solid var(--acp-border);
            border-radius: 0.5rem;
            padding: 0.75rem 1rem;
            margin-bottom: 0.75rem;
        }
        .acp-faq-item > summary {
            cursor: pointer;
            font-weight: 600;
            list-style: none;
        }
        .acp-faq-item > summary::-webkit-details-marker { display: none; }
        .acp-faq-item > summary::before {
            content: '▸';
            display: inline-block;
            margin-right: 0.5rem;
            color: var(--acp-accent);
            transition: transform 0.15s ease;
        }
        .acp-faq-item[open] > summary::before { transform: rotate(90deg); }
        .acp-faq-answer { margin-top: 0.5rem; color: var(--acp-muted); }
        .acp-faq-answer p { margin: 0.5rem 0; }
        .acp-faq-answer :first-child { margin-top: 0; }

        .acp-empty { color: var(--acp-muted); font-size: 0.9rem; }
    </style>
@endonce
