@php
    use App\Enums\ImageVariant;
    use App\Enums\ProductCardOverride;
    use App\Filament\Support\ArticleRichContent;
    use App\Models\Product;
    use App\Support\Products\ArticleProductSyncer;
    use Illuminate\Support\Facades\Storage;
    use Illuminate\Support\Str;

    $blocks = is_array($getState()) ? $getState() : [];

    // The stored path is the Original (suffix-less) variant; derive the smaller
    // -mobile.webp sibling generated by the image pipeline.
    $mobileVariant = fn (string $path): string => str_ends_with($path, '.webp')
        ? Str::replaceLast('.webp', ImageVariant::Mobile->fileSuffix() . '.webp', $path)
        : $path;

    // Ranks come from the same helper the syncer uses, so the number printed here
    // always matches the one stored on the article_product pivot. Products are
    // loaded once up front rather than per card.
    $ranks = ArticleProductSyncer::ranksFor($getRecord());
    $products = $ranks === []
        ? collect()
        : Product::with(['brand', 'affiliateLinks', 'primaryIngredient', 'ingredients'])
            ->findMany(array_keys($ranks))
            ->keyBy('id');
@endphp

<x-dynamic-component :component="$getEntryWrapperView()" :entry="$entry">
    <div class="article-content-preview">
        @forelse ($blocks as $block)
            @php
                $type = $block['type'] ?? null;
                $data = $block['data'] ?? [];
            @endphp

            @switch($type)
                @case('richText')
                    <div class="acp-block acp-richtext">
                        {{ ArticleRichContent::renderer($data['content'] ?? '') }}
                    </div>
                    @break

                @case('image')
                    @php
                        $path = $data['image'] ?? null;
                        $caption = $data['caption'] ?? null;
                    @endphp
                    @if (filled($path))
                        <figure class="acp-block acp-figure">
                            <img
                                src="{{ Storage::disk('public')->url($mobileVariant($path)) }}"
                                alt="{{ $data['alt'] ?? '' }}"
                                loading="lazy"
                            >
                            @if (filled($caption))
                                <figcaption>{{ $caption }}</figcaption>
                            @endif
                        </figure>
                    @endif
                    @break

                @case('faq')
                    <div class="acp-block acp-faq">
                        @if (filled($data['heading'] ?? null))
                            <h3 class="acp-faq-heading">{{ $data['heading'] }}</h3>
                        @endif

                        @foreach (($data['items'] ?? []) as $item)
                            <details class="acp-faq-item">
                                <summary>{{ $item['question'] ?? '' }}</summary>
                                <div class="acp-faq-answer">
                                    {{ ArticleRichContent::renderer($item['answer'] ?? '') }}
                                </div>
                            </details>
                        @endforeach
                    </div>
                    @break

                @case('productCard')
                    @php
                        $product = $products->get((int) ($data['product_id'] ?? 0));
                        $rank = $product ? ($ranks[$product->id] ?? null) : null;

                        // Inherit the product's links, override them, or show none.
                        $mode = ProductCardOverride::resolve($data['links_mode'] ?? null);
                        $links = match ($mode) {
                            ProductCardOverride::None => collect(),
                            ProductCardOverride::Custom => $product
                                ? \App\Models\AffiliateLink::findMany(
                                    is_array($data['affiliate_link_ids'] ?? null) ? $data['affiliate_link_ids'] : [],
                                )
                                : collect(),
                            ProductCardOverride::Inherit => $product ? $product->affiliateLinks : collect(),
                        };

                        // Same three-way rule for the description.
                        $description = match (ProductCardOverride::resolve($data['description_mode'] ?? null)) {
                            ProductCardOverride::None => null,
                            ProductCardOverride::Custom => $data['description'] ?? null,
                            ProductCardOverride::Inherit => $product?->description,
                        };
                    @endphp

                    {{-- A card whose product has been deleted is skipped rather than half-rendered. --}}
                    @if ($product)
                        <div class="acp-block acp-product">
                            @if ($rank !== null)
                                <div class="acp-product-rank">#{{ $rank }}</div>
                            @endif

                            <div class="acp-product-body">
                                @if (filled($product->image))
                                    <img
                                        class="acp-product-image"
                                        src="{{ Storage::disk('public')->url($mobileVariant($product->image)) }}"
                                        alt="{{ $product->name }}"
                                        loading="lazy"
                                    >
                                @endif

                                <div class="acp-product-main">
                                    <h3 class="acp-product-name">{{ $product->name }}</h3>

                                    @if ($product->brand)
                                        <p class="acp-product-brand">{{ $product->brand->name }}</p>
                                    @endif

                                    <dl class="acp-product-facts">
                                        @if (filled($product->rating))
                                            <div>
                                                <dt>Rating</dt>
                                                <dd>{{ number_format((float) $product->rating, 1) }} / 5</dd>
                                            </div>
                                        @endif
                                        @if (filled($product->price))
                                            <div>
                                                <dt>Price</dt>
                                                <dd>{{ $product->currency }} {{ number_format((float) $product->price, 2) }}</dd>
                                            </div>
                                        @endif
                                        @if (filled($product->price_per_dose))
                                            <div>
                                                <dt>Per dose</dt>
                                                <dd>{{ $product->currency }} {{ number_format((float) $product->price_per_dose, 2) }}</dd>
                                            </div>
                                        @endif
                                        @if ($product->form)
                                            <div>
                                                <dt>Form</dt>
                                                <dd>{{ $product->form->getLabel() }}</dd>
                                            </div>
                                        @endif
                                        @if ($product->composition)
                                            <div>
                                                <dt>Composition</dt>
                                                <dd>{{ $product->composition->getLabel() }}</dd>
                                            </div>
                                        @endif
                                        @if ($product->primaryIngredient)
                                            <div>
                                                <dt>Main ingredient</dt>
                                                <dd>{{ $product->primaryIngredient->name }}</dd>
                                            </div>
                                        @endif
                                        @if (filled($product->doses_per_pack))
                                            <div>
                                                <dt>Doses</dt>
                                                <dd>{{ $product->doses_per_pack }}</dd>
                                            </div>
                                        @endif
                                    </dl>

                                    @if ($product->ingredients->isNotEmpty())
                                        <p class="acp-product-ingredients">
                                            @foreach ($product->ingredients as $ingredient)
                                                <span>{{ $ingredient->name }}</span>
                                            @endforeach
                                        </p>
                                    @endif

                                    @if (filled($description))
                                        <div class="acp-product-description acp-richtext">
                                            {{ ArticleRichContent::renderer($description) }}
                                        </div>
                                    @endif

                                    @if ($links->isNotEmpty())
                                        <div class="acp-product-links">
                                            @foreach ($links as $link)
                                                {{-- /go/{slug} so the click is logged and rel is applied centrally. --}}
                                                <a
                                                    class="acp-product-buy"
                                                    href="{{ $link->redirectPath() }}"
                                                    rel="sponsored nofollow"
                                                >{{ $link->retailer ?? $link->name }}</a>
                                            @endforeach
                                        </div>
                                    @endif
                                </div>
                            </div>
                        </div>
                    @endif
                    @break
            @endswitch
        @empty
            <p class="acp-empty">This article has no content yet.</p>
        @endforelse
    </div>
</x-dynamic-component>

@include('filament.infolists.article-content-styles')
