<?php

use App\Enums\ProductStatus;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('products', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug')->unique();
            $table->foreignId('brand_id')->nullable()->constrained()->nullOnDelete();

            /**
             * The headline ingredient, so a "TOP 10 Vitamin D" grouping stays
             * unambiguous: a multivitamin contains Vitamin D but is not a
             * Vitamin D product.
             */
            $table->foreignId('primary_ingredient_id')->nullable()->constrained('ingredients')->nullOnDelete();

            $table->text('description')->nullable();
            $table->string('image')->nullable();
            $table->string('form')->nullable()->index();
            $table->string('composition')->nullable()->index();

            $table->decimal('price', 10, 2)->nullable();
            $table->unsignedInteger('doses_per_pack')->nullable();
            $table->string('currency', 3)->default('USD');

            /**
             * Generated by the database rather than an accessor so the catalog can
             * sort and filter on it. NULLIF keeps a zero or missing dose count from
             * raising a division error, yielding null instead.
             */
            $table->decimal('price_per_dose', 10, 4)
                ->nullable()
                ->storedAs('price / NULLIF(doses_per_pack, 0)');

            $table->decimal('rating', 2, 1)->nullable();
            $table->string('status')->default(ProductStatus::Draft->value)->index();
            $table->string('meta_title')->nullable();
            $table->text('meta_description')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('products');
    }
};
